# Generated by Django 4.2.4 on 2023-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='galleriesCount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='imagesCount',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
