# Generated by Django 4.2.4 on 2023-08-13 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='user',
            new_name='profile',
        ),
    ]
