# Generated by Django 4.2.4 on 2023-08-13 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_rename_user_gallery_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='profile',
        ),
        migrations.AddField(
            model_name='gallery',
            name='userId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
