# Generated by Django 4.2.4 on 2023-08-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imagesCount',
        ),
    ]
